=== andreshmb/LMSGI-03.github.io/doc/vehiculos.dtd
<?xml version="1.0" encoding="UTF-8"?>

<!ELEMENT coches  ( marca+ )>


<!ELEMENT marca  ( modelo+ )>

<!ATTLIST marca
 nombre CDATA #REQUIRED
>

<!ELEMENT modelo  (nombre ,velocidad* ,cilindrada* ,potencia* ,consumo? ,co2? ,combustible?)>

<!ATTLIST modelo
 nombre CDATA #REQUIRED
>

<!ELEMENT nombre  ( #PCDATA )>

<!ELEMENT velocidad  ( #PCDATA )>

<!ELEMENT cilindrada  ( #PCDATA )>

<!ELEMENT potencia  ( #PCDATA )>

<!ELEMENT consumo  ( #PCDATA )>

<!ELEMENT co2  ( #PCDATA )>

<!ELEMENT combustible  ( #PCDATA )>

=== andreshmb/LMSGI-03.github.io/doc/vehiculos.xml
<?xml version="1.0" encoding="UTF-8"?>

<!--Documento con lista de tipos de coches y sus caracteristicas obtenidos de la web: www.autobild.es-->

<!--Enlace al documento DTD-->

<!DOCTYPE coches SYSTEM "vehiculos.dtd">
<coches xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
		xsi:noNamespaceSchemaLocation="vehiculos.xsd">
	<marca nombre="Alfa-romeo">
		<modelo nombre="C4">
			<nombre>Alfa Romeo C4 Spider 2014
			</nombre>
			<velocidad>257 km/h
			</velocidad>
			<cilindrada>1.742 cc
			</cilindrada>
			<potencia>241 cv
			</potencia>
			<co2>161
			</co2>
			<combustible>Gasolina
			</combustible>
		</modelo>
		<modelo nombre="Stelvio">
			<nombre>Alfa Romeo Stelvio Quadrifoglio Verde 2017 2.9 V6 BiTurbo 510CV Q4 Automático
			</nombre>
			<velocidad>283 km/h
			</velocidad>
			<cilindrada>2.891 cc
			</cilindrada>
			<potencia>510 cv
			</potencia>
			<co2>210
			</co2>
			<combustible>Gasolina
			</combustible>		
		</modelo>
		<modelo nombre="Giulietta">
			<nombre>Alfa Romeo Giulietta Quadrifoglio Verde 2017
			</nombre>
			<velocidad>244 km/h
			</velocidad>
			<cilindrada>1.742 cc
			</cilindrada>
			<potencia>240 cv
			</potencia>
			<co2>157
			</co2>
			<combustible>Gasolina
			</combustible>
		</modelo>
		<modelo nombre="MiTo">
			<nombre>Alfa Romeo MiTo Quadrifoglio Verde 2017 1.4 TB 170CV TCT Veloce
			</nombre>
			<velocidad>219 km/h
			</velocidad>
			<cilindrada>1.368 cc
			</cilindrada>
			<potencia>170 cv
			</potencia>
			<co2>124
			</co2>
			<combustible>Gasolina
			</combustible>
		</modelo>
	</marca>
	<marca nombre="Audi">
		<modelo nombre="A8">
			<nombre>Audi A8 Largo 2017 55 TFSI 340CV Quattro Tiptronic
			</nombre>
			<velocidad>250 km/h
			</velocidad>
			<cilindrada>2.995 cc
			</cilindrada>
			<potencia>340 cv
			</potencia>
			<co2>180
			</co2>
			<combustible>Gasolina
			</combustible>
		</modelo>
		<modelo nombre="Q8">
			<nombre>Audi Q8 2018 55 TFSI 340CV Quattro Tiptronic
			</nombre>
			<velocidad>250 km/h
			</velocidad>
			<cilindrada>2.995 cc
			</cilindrada>
			<potencia>340 cv
			</potencia>
			<co2>
000
			</co2>
			<combustible>Gasolina
			</combustible>
		</modelo>
		<modelo nombre="R8">
			<nombre>Audi R8 Spyder 2017 5.2 FSI V10 610CV Quattro S-Tronic Plus
			</nombre>
			<velocidad>328 km/h
			</velocidad>
			<cilindrada>5.204 cc
			</cilindrada>
			<potencia>610 cv
			</potencia>
			<co2>309
			</co2>
			<combustible>Gasolina
			</combustible>
		</modelo>
		<modelo nombre="TT">
			<nombre>Audi TT RS Roadster 2017 2.5 TFSI 400CV Quattro S-Tronic
			</nombre>
			<velocidad>250 km/h
			</velocidad>
			<cilindrada>2.480 cc
			</cilindrada>
			<potencia>400 cv
			</potencia>
			<co2>189
			</co2>
			<combustible>Gasolina
			</combustible>
		</modelo>
	</marca>
	<marca nombre="BMW">
		<modelo nombre="Serie8">
			<nombre>BMW Serie 8 Coupé 2017 M850i xDrive
			</nombre>
			<velocidad>250 km/h
			</velocidad>
			<cilindrada>4.395 cc
			</cilindrada>
			<potencia>530 cv / 6.000 rpm
			</potencia>
			<consumo>10,1 l/100 km
			</consumo>
			<co2>228
			</co2>
			<combustible>Gasolina 
			</combustible>
		</modelo>
		<modelo nombre="X6">
			<nombre>BMW X6 M 2014 X6 M
			</nombre>
			<velocidad>250 km/h
			</velocidad>
			<cilindrada>4.395 cc
			</cilindrada>
			<potencia>575 cv / 6.500 rpm
			</potencia>
			<consumo>14,7
			</consumo>
			<co2>258
			</co2>
			<combustible>Gasolina
			</combustible>
		</modelo>
		<modelo nombre="Z4">
			<nombre>BMW Z4 2017 M40i
			</nombre>
			<velocidad>250 km/h
			</velocidad>
			<cilindrada>2.998 cc
			</cilindrada>
			<potencia>340 cv / 5.000 rpm
			</potencia>
			<consumo>9,2/5,9/7,1 l/100 km
			</consumo>
			<co2>162
			</co2>
			<combustible>Gasolina
			</combustible>
		</modelo>
	</marca>
	<marca nombre="Chevrolet">
		<modelo nombre="Camaro">
			<nombre>Chevrolet Camaro Convertible 2009 6.2 V8 432CV Automático
			</nombre>
			<velocidad>250 km/h
			</velocidad>
			<cilindrada>6.162 cc
			</cilindrada>
			<potencia>432 cv / 5.900 rpm
			</potencia>
			<consumo>18,9/9,7/13,1 l/100 km
			</consumo>
			<co2>304
			</co2>
			<combustible>Gasolina
			</combustible>
		</modelo>
		<modelo nombre="Corvette">
			<nombre>Chevrolet Corvette Stingray Coupe 2013 6.2 V8
			</nombre>
			<velocidad>292 km/h
			</velocidad>
			<cilindrada>6.162 cc
			</cilindrada>
			<potencia>466 cv / 6.000 rpm
			</potencia>
			<consumo>19,1/7,8/12,0 l/100 km
			</consumo>
			<co2>279
			</co2>
			<combustible>Gasolina
			</combustible>
		</modelo>
		<modelo nombre="Malibu">
			<nombre>Chevrolet Malibu 2011 2.0 VDCi 160CV LTZ
			</nombre>
			<velocidad>213 km/h
			</velocidad>
			<cilindrada>1.956 cc
			</cilindrada>
			<potencia>160 cv / 4.000 rpm
			</potencia>
			<consumo>5,8/4,2/4,7 l/100 km
			</consumo>
			<co2>125
			</co2>
			<combustible>Diesel
			</combustible>
		</modelo>
		<modelo nombre="Volt">
			<nombre>Chevrolet Volt 2011 1.4 86CV Automático
			</nombre>
			<velocidad>160 km/h
			</velocidad>
			<cilindrada>1.398 cc
			</cilindrada>
			<potencia>86 cv / 4.800 rpm
			</potencia>
			<consumo>0,0/0,0/1,2 l/100 km
			</consumo>
			<co2>27
			</co2>
			<combustible>Gasolina
			</combustible>
		</modelo>
	</marca>
	<marca nombre="Citroen">
		<modelo nombre="Cactus">
			<nombre>Citroën C4 Cactus 2017 PureTech 130 Shine
			</nombre>
			<velocidad>207 km/h
			</velocidad>
			<cilindrada>1.199 cc
			</cilindrada>
			<potencia>130 cv / 5.500 rpm
			</potencia>
			<consumo>6,1/4,1/4,8 l/100 km
			</consumo>
			<co2>110
			</co2>
			<combustible>Gasolina
			</combustible>
		</modelo>
		<modelo nombre="E-Mehari">
			<nombre>Citroën E-Mehari 2017 Full Electric
			</nombre>
			<velocidad>110 km/h
			</velocidad>
			<cilindrada>1.500 cc
			</cilindrada>
			<potencia>65 cv
			</potencia>
			<consumo>0,00/0,00/0,00 l/100 km
			</consumo>
			<co2>
000
			</co2>
			<combustible>Electrico
			</combustible>
		</modelo>
		<modelo nombre="Spacetourer">
			<nombre>Citroën Spacetourer 2015 BlueHDi 180 EAT6 Shine XL
			</nombre>
			<velocidad>170 km/h
			</velocidad>
			<cilindrada>1.997 cc
			</cilindrada>
			<potencia>177 cv / 3.750 rpm
			</potencia>
			<consumo>6,3/5,5/5,9 l/100 km
			</consumo>
			<co2>155
			</co2>
			<combustible>Diesel
			</combustible>
		</modelo>
		<modelo nombre="C-Zero">
			<nombre>Citroën C-Zero 2010 Airdream Seduction
			</nombre>
			<velocidad>130 km/h
			</velocidad>
			<cilindrada>
			</cilindrada>
			<potencia>67 cv / 3.500 rpm
			</potencia>
			<consumo>0,0/0,0/0,0 l/100 km
			</consumo>
			<co2>
000
			</co2>
			<combustible>Electrico
			</combustible>
		</modelo>
	</marca>
	<marca nombre="Ferrari">
		<modelo nombre="488">
			<nombre>Ferrari 488 GTB Spider 2015 3.9 V8 670CV
			</nombre>
			<velocidad>325 km/h
			</velocidad>
			<cilindrada>3.902 cc
			</cilindrada>
			<potencia>670 cv / 8.000 rpm
			</potencia>
			<consumo>0,0/0,0/11,4 l/100 km
			</consumo>
			<co2>260
			</co2>
			<combustible>Gasolina
			</combustible>
		</modelo>
		<modelo nombre="812">
			<nombre>Ferrari 812 Superfast 2017 6.5 V12 799CV
			</nombre>
			<velocidad>340 km/h
			</velocidad>
			<cilindrada>6.496 cc
			</cilindrada>
			<potencia>799 cv / 8.500 rpm
			</potencia>
			<consumo>0,0/0,0/14,9 l/100 km
			</consumo>
			<co2>340
			</co2>
			<combustible>Gasolina
			</combustible>
		</modelo>
		<modelo nombre="California">
			<nombre>Ferrari California T 2008 3.8 V8 560CV
			</nombre>
			<velocidad>316 km/h
			</velocidad>
			<cilindrada>3.855 cc
			</cilindrada>
			<potencia>560 cv / 7.500 rpm
			</potencia>
			<consumo>0,00/0,00/10,5 l/100 km
			</consumo>
			<co2>250
			</co2>
			<combustible>Gasolina
			</combustible>
		</modelo>
		<modelo nombre="F12">
			<nombre>Ferrari F12 Berlinetta 2012 6.2 V12 780CV F12tdf
			</nombre>
			<velocidad>340 km/h
			</velocidad>
			<cilindrada>6.262 cc
			</cilindrada>
			<potencia>780 cv / 8.500 rpm
			</potencia>
			<consumo>0,0/0,0/15,4 l/100 km
			</consumo>
			<co2>360
			</co2>
			<combustible>Gasolina
			</combustible>
		</modelo>
	</marca>
	<marca nombre="Ford">
		<modelo nombre="GT">
			<nombre>Ford GT 2017 3.5 Twin-Turbo EcoBoost V6
			</nombre>
			<velocidad>347 km/h
			</velocidad>
			<cilindrada>3.497 cc
			</cilindrada>
			<potencia>647 cv / 6.250 rpm
			</potencia>
			<consumo>0,0/0,0/16,8 l/100 km
			</consumo>
			<co2>395
			</co2>
			<combustible>Gasolina
			</combustible>
		</modelo>
		<modelo nombre="Mustang">
			<nombre>Ford Mustang Fastback 2015 5.0 Ti-VCT V8 418CV Automático GT
			</nombre>
			<velocidad>250 km/h
			</velocidad>
			<cilindrada>4.951 cc 
			</cilindrada>
			<potencia>418 cv / 6.500 rpm
			</potencia>
			<consumo>-/-/12 l/100 km
			</consumo>
			<co2>281
			</co2>
			<combustible>Gasolina
			</combustible>
		</modelo>
		<modelo nombre="Ranger">
			<nombre>Ford Ranger 2016 3.2 TDCI 200CV AWD Doble Cabina Wildtrack Automático
			</nombre>
			<velocidad>175 km/h
			</velocidad>
			<cilindrada>3.198 cc
			</cilindrada>
			<potencia>200 cv / 3.000 rpm
			</potencia>
			<consumo>11,4/7,4/8,9 l/100 km 
			</consumo>
			<co2>234
			</co2>
			<combustible>Diesel
			</combustible>
		</modelo>
	</marca>
	<marca nombre="Honda">
		<modelo nombre="HR-V">
			<nombre>Honda HR-V 2015 1.5 i-VTEC 130CV Comfort
			</nombre>
			<velocidad>192 km/h
			</velocidad>
			<cilindrada>1.498 cc
			</cilindrada>
			<potencia>130 cv / 6.600 rpm
			</potencia>
			<consumo>7,0/4,8/5,6 l/100 km
			</consumo>
			<co2>130
			</co2>
			<combustible>Gasolina
			</combustible>
		</modelo>
		<modelo nombre="Jazz">
			<nombre>Honda Jazz 2016 1.5 i-VTEC 130CV Dynamic CVT
			</nombre>
			<velocidad>190 km/h
			</velocidad>
			<cilindrada>1.498 cc
			</cilindrada>
			<potencia>130 cv / 6.600 rpm
			</potencia>
			<consumo>6,4/4,9/5,4 l/100 km
			</consumo>
			<co2>124
			</co2>
			<combustible>Gasolina
			</combustible>
		</modelo>
		<modelo nombre="NSX">
			<nombre>Honda NSX 2016 3.5 V6 581CV
			</nombre>
			<velocidad>308 km/h
			</velocidad>
			<cilindrada>3.493 cc
			</cilindrada>
			<potencia>507 cv / 6.500 rpm
